version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app                  # 👈 Mount entire backend folder
    working_dir: /app                  # 👈 Default path inside container
    environment:
      - PYTHONPATH=/app                # 👈 Set root for import paths
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: spond_user
      POSTGRES_PASSWORD: spond_pass
      POSTGRES_DB: spond_clone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
